AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  CommunityFridgeMapApi

  SAM Template for CommunityFridgeMapApi

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Parameters:
  Environment:
    Type: String
    Description: Choose between local or AWS
    AllowedValues:
      - local
      - aws

##########################
##    Resources    ##
##########################
Resources:
  FridgeReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/fridge_reports
      Handler: app.lambda_handler
      Runtime: python3.9
      FunctionName: FridgeReportFunction
      Environment:
        Variables:
          Environment: !Ref Environment
      Layers:
        - !Ref CommonLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - dynamodb:PutItem
            Resource: !GetAtt FridgeReportTable.Arn
      Events:
        FridgeReport:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/fridges/{fridge_id}/reports
            Method: post
            RequestParameters:
              - method.request.path.fridge_id:
                  Required: true
                  Caching: false

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/dev/hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Layers:
        - !Ref CommonLayer
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  FridgesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/fridges/v1
      Handler: app.lambda_handler
      Runtime: python3.9
      FunctionName: FridgesFunction
      Environment:
        Variables:
          Environment: !Ref Environment
      Layers:
        - !Ref CommonLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:PutItem
            Resource: !GetAtt FridgeTable.Arn
      Events:
        GetFridge:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/fridges/{fridge_id}
            Method: get
            RequestParameters:
              - method.request.path.fridge_id:
                  Required: false
                  Caching: false
        GetFridges:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/fridges
            Method: get
            RequestParameters:
              - method.request.querystring.tag:
                  Required: false

  LoadFridgeDataFunction: #FOR DEV TESTING PURPOSES ONLY. TODO: DELETE THIS FUNCTION
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions/dev/load_fridge_data
      Handler: app.lambda_handler
      Runtime: python3.9
      FunctionName: LoadFridgeDataFunction
      Environment:
        Variables:
          Environment: !Ref Environment
      Layers:
        - !Ref CommonLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - dynamodb:PutItem
            Resource: !GetAtt FridgeTable.Arn
    ##########################
    ##    Layers    ##
    ##########################
  CommonLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: CommunityFridgeMapApiLayer
            Description: Dependencies for CommunityFridgeMapApi project
            ContentUri: dependencies/
            CompatibleRuntimes:
              - python3.7
              - python3.8
              - python3.9
            RetentionPolicy: Delete
  ##########################
  ##    DynamoDB Tables    ##
  ##########################

  FridgeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      TableName: fridge
      BillingMode: "PAY_PER_REQUEST"

  FridgeReportTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "fridge_id"
          AttributeType: "S"
        - AttributeName: "epochTimestamp" #epoch time used for querying data
          AttributeType: "N"
      KeySchema:
        - AttributeName: "fridge_id"
          KeyType: "HASH"
        - AttributeName: "epochTimestamp"
          KeyType: "RANGE"
      TableName: fridge_report
      BillingMode: "PAY_PER_REQUEST"

  TagTable:
    Type: AWS::DynamoDB::Table
    Properties:

      AttributeDefinitions:
        - AttributeName: "tag_name"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "tag_name"
          KeyType: "HASH"
      TableName: tag
      BillingMode: "PAY_PER_REQUEST"

  FridgeHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "fridge_id"
          AttributeType: "S"
        - AttributeName: "epochTimestamp" #epoch time used for querying data
          AttributeType: "N"
      KeySchema:
        - AttributeName: "fridge_id"
          KeyType: "HASH"
        - AttributeName: "epochTimestamp"
          KeyType: "RANGE"
      TableName: fridge_history
      BillingMode: "PAY_PER_REQUEST"


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
