AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CommunityFridgeMapApi

  SAM Template for CommunityFridgeMapApi

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Environment:
      Variables:
        TABLE_NAME: my-table
        FRIDGE_TABLE_NAME: fridge
        FRIDGE_CHECKIN_TABLE_NAME: fridge_check_in
        FRIDGE_HISTORY_TABLE_NAME: fridge_history
        TAG_TABLE_NAME: tag

Parameters:
  Environment:
    Type: String
    Description: Choose between local or AWS
    AllowedValues:
      - local
      - aws

##########################
##    Resources    ##
##########################
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/dev/hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Layers:
        - !Ref CommonLayer
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  GetAllFunction: #FOR DEV TESTING PURPOSES ONLY. TODO: DELETE THIS FUNCTION
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/dev/get_all/
      Handler: app.lambda_handler
      Runtime: python3.9
      FunctionName: GetAllFunction
      Events:
        GetDocument:
          Type: Api
          Properties:
            Path: /get_all
            Method: get
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          Environment: !Ref Environment
          FridgeTableName: "fridge"
      Layers:
        - !Ref CommonLayer
      Policies:
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - dynamodb:getItem
            Resource: !GetAtt FridgeTable.Arn
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
          
  LoadFridgeDataFunction: #FOR DEV TESTING PURPOSES ONLY. TODO: DELETE THIS FUNCTION
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./functions/dev/load_fridge_data
      Handler: app.lambda_handler
      Runtime: python3.9
      FunctionName: LoadFridgeDataFunction
      Environment:
        Variables:
          Environment: !Ref Environment
      Layers:
        - !Ref CommonLayer
      Policies:
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - dynamodb:BatchWriteItem
            Resource: !GetAtt FridgeTable.Arn

    GetIndivFridgeFunction:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: functions/get_indiv_fridge
        Handler: app.lambda_handler
        Runtime: python3.9
        FunctionName: GetIndivFridgeFunction
        Environment:
          Variables:
            Environment: !Ref Environment
        Layers:
          - !Ref CommonLayer
        Policies:
          - Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
              - dynamodb:BatchWriteItem
              Resource: !GetAtt FridgeTable.Arn

              
    ##########################
    ##    Layers    ##
    ##########################
  CommonLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: CommunityFridgeMapApiLayer
            Description: Dependencies for CommunityFridgeMapApi project
            ContentUri: dependencies/
            CompatibleRuntimes:
              - python3.7
              - python3.8
              - python3.9
            RetentionPolicy: Delete
  ##########################
  ##    DynamoDB Tables    ##
  ##########################

  FridgeTable:
    TableName: !Ref FRIDGE_TABLE_NAME
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: 'username'
          AttributeType: 'S'
        - 
          AttributeName: 'display_name'
          AttributeType: 'S'
        - 
          AttributeName: "address"
          AttributeType: "S"
        - 
          AttributeName: "instagram"
          AttributeType: "S"
        - 
          AttributeName: "last_edited"
          AttributeType: "N"
        - 
          AttributeName: "info"
          AttributeType: "S"
        - 
          AttributeName: "url"
          AttributeType: "S"
        - 
          AttributeName: "neighborhood"
          AttributeType: "S"
        - 
          AttributeName: "organizer_email"
          AttributeType: "S"
        - 
          AttributeName: "tags"
          AttributeType: "L"
        - 
          AttributeName: "food_accepts"
          AttributeType: "L"
        - 
          AttributeName: "food_restrictions"
          AttributeType: "L"
        - 
          AttributeName: "lat"
          AttributeType: "S"
        - 
          AttributeName: "long"
          AttributeType: "S"
        - 
          AttributeName: "profile_image"
          AttributeType: "S"
        - 
          AttributeName: "check_in_time"
          AttributeType: "S"
        - 
          AttributeName: "check_in_notes"
          AttributeType: "S"
        - 
          AttributeName: "check_in_status"
          AttributeType: "S"
        - 
          AttributeName: "check_in_image"
          AttributeType: "S"
        - 
          AttributeName: "fridge_state"
          KeyType: "S"
      KeySchema: 
        -
          AttributeName: "fridge_state"
          KeyType: "HASH"
        -
          AttributeName: "username"
          KeyType: "RANGE"                           
      BillingMode: 'PAY_PER_REQUEST'
  
  FridgeCheckInTable:
    TableName: !Ref FRIDGE_CHECKIN_TABLE_NAME
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: 'notes'
          AttributeType: 'S'
        - 
          AttributeName: "status"
          AttributeType: "N"
        - 
          AttributeName: "image"
          AttributeType: "S"
        - 
          AttributeName: "#fridge_state#fridge_username"
          KeyType: "S"
        - 
          AttributeName: "timestamp"
          KeyType: "N"
      KeySchema: 
        - #State#FridgeName
          AttributeName: "#fridge_state#fridge_username"
          KeyType: "HASH"
        -
          AttributeName: "timestamp"
          KeyType: "RANGE"                           
      BillingMode: 'PAY_PER_REQUEST'

  TagTable:
    TableName: !Ref TAG_TABLE_NAME
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: 'tag_name'
          AttributeType: 'S'
      KeySchema: 
        -
          AttributeName: "tag_name"
          KeyType: "HASH"                       
      BillingMode: 'PAY_PER_REQUEST'

  FridgeHistoryTable:
    TableName: !Ref FRIDGE_HISTORY_TABLE_NAME
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: '#fridge_state#fridge_username'
          AttributeType: 'S'
        - 
          AttributeName: "address"
          AttributeType: "S"
        - 
          AttributeName: "instagram"
          AttributeType: "S"
        - 
          AttributeName: "last_edited"
          AttributeType: "N"
        - 
          AttributeName: "info"
          AttributeType: "S"
        - 
          AttributeName: "url"
          AttributeType: "S"
        - 
          AttributeName: "neighborhood"
          AttributeType: "S"
        - 
          AttributeName: "organizer_email"
          AttributeType: "S"
        - 
          AttributeName: "tags"
          AttributeType: "L"
        - 
          AttributeName: "food_accepts"
          AttributeType: "L"
        - 
          AttributeName: "food_restrictions"
          AttributeType: "L"
        - 
          AttributeName: "lat"
          AttributeType: "S"
        - 
          AttributeName: "long"
          AttributeType: "S"
        - 
          AttributeName: "profile_image"
          AttributeType: "S"
        - 
          AttributeName: "check_in_time"
          AttributeType: "S"
        - 
          AttributeName: "check_in_notes"
          AttributeType: "S"
        - 
          AttributeName: "check_in_status"
          AttributeType: "S"
        - 
          AttributeName: "check_in_image"
          AttributeType: "S"
        - 
          AttributeName: "pk"
          KeyType: "S"
        - 
          AttributeName: "timestamp"
          KeyType: "N"
      KeySchema: 
        -
          AttributeName: "#fridge_state#fridge_username"
          KeyType: "HASH"
        -
          AttributeName: "timestamp"
          KeyType: "RANGE"                           
      BillingMode: 'PAY_PER_REQUEST'


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
